#!/usr/bin/env python3

import time
import colors as c
import sys

print(c.clear+c.orange)
try:
    if len(sys.argv)==1:
        to=input("What would you like to count to? ")
    else:
        to=int(sys.argv[1])
escept ValueError:
    print("Oops, invalid number!")
    quit()#Temporary, as program is non-functional w/o it
print(c.clear)
print('Counting to '+str(to))

try:
    for count in range(int(to)):
        print(str(count)+" seconds")
        time.sleep(1)
    print(str(to)+' seconds, Done!')
except KeyboardInterrupt:
    print("losing the program already?")
