#!/usr/bin/env python3

import time
import colors as c
import sys

print(c.clear+c.orange)
try:
    if len(sys.argv)==1:
        to=input("What would you like to count to? ")
    else:
        to=int(sys.argv[1])
    print(c.clear)
    print('Counting to '+str(to))
    for count in range(int(to)):
        print(str(count)+" seconds")
        time.sleep(1)
    print(str(to)+' seconds, Done!')
except ValueError:
    print("Oops, invalid number!")

except KeyboardInterrupt:
    print("losing the program already?")
