#!/usr/bin/env python3
import colors as c

print(c.clear)
print(c.red+"Aloha! What name hath thee?")
name=input(c.blue+"> ").strip().title()
print(c.red+"Well it's nice to meet you, "+c.blue+name)
print(c.red+"My name just so happens to not be"+c.blue+" {}".format(name))
