#!/usr/bin/env python3

import random
import colors as c
answers=[
    'yes',
    'Why would I tell you?',
    'no',
    'derp',
    'Ask your parents',
    "DID SOMEONE SAY SALSA?",
    '''
    ____        __
   / __ )____  / /_  ___
  / __  / __ \/ __ \/ _ \\
 / /_/ / /_/ / /_/ /  __/
/_____/\____/_____/\___/
''',
    'nope',
    "That's a stupid query",
    "I'LL NEVER TELL YOU",
    'Nein',
    'hahahahahahahano',
    'In your dreams',
    'nah',
    "I don't know, I'm not magic... wait..",
    'that depends....',
    "I'll tell ya later",
    'SÍ SEÑOR',
    'idk, bruh',
    'NO SEÑOR'
]

print(c.clear)
def query():
    print(c.reset+"To exit, press Ctrl+C")
    print('ENTER YOUR QUERY')
    q=input(c.random_color()+'>> ').strip().lower()
    if "salsa" in q:
        print('''
        ███████╗ █████╗ ██╗     ███████╗ █████╗ ██╗
        ██╔════╝██╔══██╗██║     ██╔════╝██╔══██╗██║
        ███████╗███████║██║     ███████╗███████║██║
        ╚════██║██╔══██║██║     ╚════██║██╔══██║╚═╝
        ███████║██║  ██║███████╗███████║██║  ██║██╗
        ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝''')
    elif "qwe" in q:
        print("QWE"*9001)
    elif "tomorrow" in q:
        print("I'll tell ya tomorrow")
    elif 'how does one jump on a lake' in q:
        print('with skill and finesse')
    else:
        a=random.choice(answers)
        print(a)

try:
    while True:
        query()
except KeyboardInterrupt:
    print(c.clear+"Bye!")
