#!/usr/bin/env python3

import random as r
import colors as c
import time as t
import sys
sides=[None]

sides.append(''' -------
|       |
|   •   |
|       |
 -------''')

sides.append(''' -------
| •     |
|       |
|     • |
 -------''')

sides.append(''' -------
| •     |
|   •   |
|     • |
 -------''')

sides.append(''' -------
| •   • |
|       |
| •   • |
 -------''')

sides.append(''' -------
| •   • |
|   •   |
| •   • |
 -------''')

sides.append(''' -------
| •   • |
| •   • |
| •   • |
 -------''')

print(c.red+c.clear)
if len(sys.arvg)!=2
print('To quit, press Ctrl+C at any time.')
dice=0

try:
    while True:
        for c in range(int(sys.argv[1])):
            print(sides[r.randint(1,6)])
        input('Press Enter to roll again, press Ctrl+C to quit')
except ValueError:
    print('Invalid Number!')
except KeyboardInterrupt:
    print('Buh-Bye!')
except IndexError:
    print('Usage: roll2 [number of dice]')
