#!/usr/bin/env python3
import time as t
import colors as c
seconds=0
print(c.clear+c.orange)
print("Press Ctrl+C at any time to quit")
input("Press enter to begin")
try:
    while True:
        print(str(seconds)+" Seconds")
        t.sleep(1)
        seconds += 1
except KeyboardInterrupt:
    print('ee-Lo Green')
