#!/usr/bin/env python3
import time as t
for count in range(5):
    for count in range(11):
        print('Badger!')
        t.sleep(.4)
        t.sleep(.4)
    for count in range(2):
        print('Mushroom!')
        t.sleep(.4)
        t.sleep(.4)
print("It's a snaaaaaaaaake!")

